<?php

use Illuminate\Database\Seeder;

class AuthorMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('author_masters')->insert([
            [
                'author'=> '夏目 漱石',
                'image'=>'creator1.png',
                'category'=>'小説家',
                'masterpiece'=>'吾輩は猫である、坊ちゃん',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '芥川 龍之介',
                'image'=>'creator2.png',
                'category'=>'小説家',
                'masterpiece'=>'羅生門、蜘蛛の糸',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '太宰 治',
                'image'=>'creator3.png',
                'category'=>'小説家',
                'masterpiece'=>'人間失格',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '井上 雄彦',
                'image'=>'creator4.png',
                'category'=>'漫画家',
                'masterpiece'=>'スラムダンク、バカボンド',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '村上 春樹',
                'image'=>'creator5.png',
                'category'=>'小説家',
                'masterpiece'=>'海辺のカフカ、ノルウェイの森',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '手塚 治虫',
                'image'=>'creator6.png',
                'category'=>'漫画家',
                'masterpiece'=>'鉄腕アトム、ブラックジャック',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '宮崎 駿',
                'image'=>'creator7.png',
                'category'=>'アニメーター',
                'masterpiece'=>'千と千尋の神隠し、もののけ姫',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> 'シェイクスピア',
                'image'=>'creator8.png',
                'category'=>'劇作家',
                'masterpiece'=>'ハムレット、ロミオとジュリエット',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> 'J・K・ローリング',
                'image'=>'creator9.png',
                'category'=>'小説家',
                'masterpiece'=>'ハリー・ポッターシリーズ',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '司馬 遼太郎',
                'image'=>'creator10.png',
                'category'=>'小説家',
                'masterpiece'=>'坂の上の雲、竜馬がゆく',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '東野 圭吾',
                'image'=>'creator11.png',
                'category'=>'小説家',
                'masterpiece'=>'容疑者Xの献身、ラプラスの魔女',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '三島 由紀夫',
                'image'=>'creator12.png',
                'category'=>'小説家',
                'masterpiece'=>'金閣寺、仮面の告白',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '水木 しげる',
                'image'=>'creator13.png',
                'category'=>'漫画家',
                'masterpiece'=>'ゲゲゲの鬼太郎、悪魔くん',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '宮下 奈都',
                'image'=>'creator14.png',
                'category'=>'小説家',
                'masterpiece'=>'羊と鋼の森、誰かが足りない',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '新海 誠',
                'image'=>'creator15.png',
                'category'=>'アニメーション監督',
                'masterpiece'=>'天気の子、君の名は。',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> 'ドフトエフスキー',
                'image'=>'creator16.png',
                'category'=>'小説家',
                'masterpiece'=>'罪と罰、カラマーゾフの兄弟',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '辻村 深月',
                'image'=>'creator17.png',
                'category'=>'小説家',
                'masterpiece'=>'かがみの孤城、スロウハイツの神様',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '又吉 直樹',
                'image'=>'creator18.png',
                'category'=>'小説家',
                'masterpiece'=>'火花、劇場',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '上橋 菜穂子',
                'image'=>'creator19.png',
                'category'=>'小説家',
                'masterpiece'=>'獣の奏者、鹿の王',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'author'=> '百田 尚樹',
                'image'=>'creator20.png',
                'category'=>'小説家',
                'masterpiece'=>'海賊とよばれた男、永遠の0',
                'default_color'=>'#F0F0F0',
                'average_color'=>'#F0F0F0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

        ]);
    }
}
